__author__ = 'Faris Chugthai'
__copyright__ = 'Copyright (C) 2018 Faris Chugthai'
__description__ = 'Automates the process of setting up a development workstation on an Ubuntu OS.'
__license__ = 'MIT'
__name__ = 'newbuntu'
__version__ = '0.1.0'
